api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView


urlpatterns = [
    path("auth/token/", TokenObtainPairView.as_view(), name="auth_token"),
    path("category/", views.CategoryListView.as_view(), name="category_list"),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name="category_detail"),
    path("sale/", views.SaleListView.as_view(), name="sale_list"),
    path("sale/<int:pk>/", views.SaleDetailView.as_view(), name="sale_detail"),
]

billboard/api/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

urlpatterns = [
    path("category/", views.CategoryListView.as_view(), name="category_list"),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name="category_detail"),
    path("sale/", views.SaleListView.as_view(), name="sale_list"),
    path("sale/<int:pk>/", views.SaleDetailView.as_view(), name="sale_detail"),
]

billboard/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>", views.category_sales, name="category_sales"),
    path("sale/<int:sale_pk>", views.sale_info, name="sale_info"),
]

ufanet_practice/urls.py
from django.urls import include, path
from django.contrib import admin
from django.shortcuts import redirect
from . import views


urlpatterns = [
    path("", views.index),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("api/", include(("api.urls", "api"), namespace="api")),
    path("billboard/", include(('billboard.urls', "billboard"), namespace="billboard")),
    path("account/", include(("account.urls", "account"), namespace="account")),
]

billboard/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField("Заголовок", max_length=30)
    photo = models.ImageField("Фото", upload_to ='static/media/', default="static/media/category-new_MROs2uS.png")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["id"]


class Sale(models.Model):
    title = models.CharField("Заголовок", max_length=50)
    subtitle = models.CharField("Подзаголовок", max_length=50, null=True, blank=True)
    description = models.TextField("Описание")

    photo = models.ImageField("Фото", upload_to ='static/media/', default="static/media/category-new_MROs2uS.png")
    promocode = models.CharField("Промокод", max_length=20, null=True, blank=True)
    url = models.URLField("Ссылка", blank=True, null=True)
    about_partner = models.TextField("О партнере")
    start_date = models.DateField("Начало акции")
    end_date = models.DateField("Окончание акции")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Скидка"
        verbose_name_plural = "Скидки"
        ordering = ["id"]

billboard/api/views.py
from rest_framework import generics
from billboard.models import Sale, Category
from billboard.api.serializers import SaleSerializer, CategorySerializer
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator


class SaleListView(generics.ListCreateAPIView):
    queryset = Sale.objects.all()
    serializer_class = SaleSerializer


    @method_decorator(cache_page(60 * 15))
    def get(self, *args, **kwargs):
        return super().get(*args, **kwargs)


class SaleDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Sale.objects.all()
    serializer_class = SaleSerializer


    @method_decorator(cache_page(60 * 15))
    def get(self, *args, **kwargs):
        return super().get(*args, **kwargs)



class CategoryListView(generics.ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


    @method_decorator(cache_page(60 * 15))
    def get(self, *args, **kwargs):
        return super().get(*args, **kwargs)


class CategoryDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


    @method_decorator(cache_page(60 * 15))
    def get(self, *args, **kwargs):
        return super().get(*args, **kwargs)

billboard/views.py
from django.shortcuts import render
from .models import Category, Sale
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from confluent_kafka import Producer
import json
from django.forms.models import model_to_dict
import datetime
import uuid

conf = {'bootstrap.servers': 'localhost:29092'}

producer = Producer(conf)

TOPIC_SALE = 'wal_listener.public_billboard_sale'
TOPIC_CATEGORY = 'wal_listener.public_billboard_category'

def model_to_json(model):
    data_model = model_to_dict(model)
    print(str(uuid.uuid1()))
    json_data = {
        "id": uuid.uuid1(),
        "data": data_model,
        "schema": "public",
        "action": "SELECT",
        "dataOld": {},
        "commitTime": datetime.datetime.now()
    }
    json_data["data"]["photo"] = model.photo.url

    if "end_date" in data_model.keys():
        json_data["table"] = "billboard_sale"
    else:
        json_data["table"] = "billboard_category"

    return json.dumps(json_data, default=str)


def post_to_topic(model, topic):
    producer.produce(topic, value=model_to_json(model), callback=delivery_report)
    producer.poll(0)
    producer.flush()


def delivery_report(err, msg):
    if err is not None:
        print(f'Ошибка доставки сообщения: {err}')
    else:
        print(f'Сообщение доставлено в {msg.topic()} [{msg.partition()}]')


@login_required
def index(request):
    if request.method == "POST":
        sale_search = request.POST.get("sale_search", "").lower()

        query = Q(title__icontains=sale_search)
        query.add(Q(subtitle__icontains=sale_search), Q.OR)
        query.add(Q(about_partner__icontains=sale_search), Q.OR)
        query.add(Q(description__icontains=sale_search), Q.OR)

        sales = Sale.objects.filter(query)
        context = {
            "sales": sales,
            "categories": [],
        }
    else:
        categories = Category.objects.all()
        sales = Sale.objects.all()
        context = {
            "categories": categories,
            "sales": sales,
        }
    return render(request, "billboard/index.html", context=context)


@login_required
def category_sales(request, pk):
    category = Category.objects.get(pk=pk)
    context = {
        "category_title": category.title,
        "sales": category.sale_set.all()
    }
    post_to_topic(category, TOPIC_CATEGORY)
    return render(request, "billboard/category_sales.html", context=context)


@login_required
def sale_info(request, sale_pk):
    sale = Sale.objects.get(pk=sale_pk)
    context = {
        "sale": sale
    }
    post_to_topic(sale, TOPIC_SALE)
    return render(request, "billboard/sale_info.html", context=context)

templates/billboard/category_sales.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div>
    <h2 id="ufanet-title">{{ category_title }}</h2>
</div>
<a href="{% url 'billboard:index'%}">&lt; Назад</a>
{% if sales %}
{% for sale in sales %}
    <a href="{% url 'billboard:sale_info' sale.pk %}">
        <div class="wrapper">
            <button>
                <div>
                    <img class="img-center" src="{{ sale.photo.url }}"/>
                    <p>{{ sale.title }} </p>
                    <p>{{ sale.subtitle }} </p>
                    <p>{{ sale.abour_partner }} </p>
                </div>
            </button>
        </div>
    </a>
{% endfor %}
{% else %}
<p>Здесь пока нет предложений, <a href="{% url 'billboard:index' %}"> лучше перейдите на главную страницу</a></p>
{% endif %}
{% endblock content %}

templates/billboard/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<form action="{% url 'billboard:index'%}" method="post">
    {% csrf_token %}
    <input type="search" placeholder="Поиск предложений" id="sale_search" name="sale_search" />
    <button>Найти</button>
</form>
{% if categories %}
    <h2 id="ufanet-title">Скидки от партнеров</h2>
{% endif %}
{% for category in categories %}
    <a href="{% url 'billboard:category_sales' category.pk %}">
        <div class="wrapper">
            <button>
            <div>
                <img class="img-center" src="{{ category.photo.url }}"/>
                {{ category.title }} <br>
                {% if category.sale_set.count > 0 %}
                    <p> Количество предложений: {{ category.sale_set.count }}</p>    
                {% else %}
                    <p>Предложений нет</p>
                {% endif %}
            </div>
            </button>
        </div>
    </a>
{% endfor %}
<h2 id="ufanet-title">Предложения</h2>
{% if sales %}
{% for sale in sales %}
    <a href="{% url 'billboard:sale_info' sale.pk %}">
        <div class="wrapper">
            <button>
                <div>
                <img class="img-center" src="{{ sale.photo.url }}"/>
                {{ sale.title }} <br>
                {{ sale.subtitle }} <br>
                {{ sale.abour_partner }} <br>
                </div>
            </button>
        </div>
    </a>
{% endfor %}
{% else %}
<p> Поищите что нибудь другое</p>
{% endif %}

{% endblock content %}

templates/billboard/sale_info.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<a href="{% url 'billboard:category_sales' sale.category.pk %}">&lt; Назад</a>
<div class="wrapper">
    <div>
        <img class="img-center" src="{{ sale.photo.url }}"/>
        <h2>{{ sale.title }} </h2>

        {% if sale.subtitle %} 
            <h3>{{ sale.subtitle }} </h3> <br>
        {% endif %}

        {% if sale.url %}
            <a href="{{sale.url}}">
                <button class="button_url"> Перейти на сайт </button>
            </a> <br>
        {% endif %}

        {% if sale.promocode %}
            <h2>Промокод</h2>
            <p>{{ sale.promocode }} </p>
        {% endif %}

        <h2>Как получить</h2>
        <p>{{ sale.description }} </p>

        <h2>О партнере</h2>
        <p>{{ sale.about_partner }} </p>
    </div>
</div>
{% endblock content %}